soulfind-dev/soulfind

- src/client.d
- src/messages.d
- src/server.d
Fixes #4
+ Added: Read the MD5 `hash` _(not implemented)_ and `minv` _(minor?)_ parameters of the `ULogin` (code `1`) request
+ Added: Implement `minv` value in `User` class variable `minor_version`
+ Changed: Renamed `User` class variable `cversion` to `major_version`
+ Added: Append `minor_version` in "User logging in" console message
+ Added: Append `minor_version` in `get_motd()` function, move call after `add_user()` to get data from `user_list`
+ Added: Append `minor_version` in `info` admin command
This value is required to filter certain client versions or perhaps alter the server's behaviour depending upon which features are supported by a particular peer's client (for example, forward distributed search requests to `160.2` clients but not for `160.1`).
> read minor version of client during Login request

- src/db.d
+ Fixed: Don't allow adding an already existing user into the admin table multiple times.
+ Changed: Enforce unique usernames in the users table.
This will also allow replacing the level value of an existing admin, were it to be implemented.
> db.d: enforce unique usernames

- src/db.d
+ Changed: Use the new [sqlite3_prepare_v2()](https://sqlite.org/c3ref/prepare.html) routine since using legacy sqlite3_prepare() is discouraged nowadays
+ Removed: [sqlite3_reset()](https://sqlite.org/c3ref/reset.html) is no longer required, since [sqlite3_step()](https://sqlite.org/c3ref/step.html) procedure resets implicitly if prepared with v2
+ Added: [sqlite3_finalize()](https://sqlite.org/c3ref/finalize.html) with v2 provides 74 [Extended Result Codes](https://sqlite.org/rescode.html#extrc) in addition to 31 Primary Result Codes
+ Fixed: Finalize immediately after each transaction to help prevent resource leaks
+ Changed: Throw the short text string description of the final result code instead of duplicating the query string
> db.d: finalize after query to output extended result codes

- src/client.d
- src/server.d
Is is a bad idea for enormous strings to be primary keys in a WITHOUT ROWID table, it works best if keys are < 50 bytes or so. This PR aims to avoid a potential performance issue during lookups whilst also being compliant with the protocol.
- Changed: Maximum new username length from 1,000,000,000 (a thousand million) characters to `30` (thirty)
- Changed: Maximum roomname length to `24`
- Changed: Validate username and roomname input strings as [printable ASCII](https://dlang.org/library/std/ascii/is_printable.html) instead of UTF
- Added: Reject usernames and roomnames containing `"  "` (double-spaces), with possiblity for excluding other strings
- Added: Reject names that are only a [punctuation](https://dlang.org/library/std/ascii/is_punctuation.html) symbol (but still allow other …
> server.d: username and roomname character set length limits

- NEWS.md
- README.md
- src/defines.d
There isn't going to be any sort of major version release, since this is a research and development effort only, it's likely to remain in alpha indefinitely, so the version ought to remain minor in order to make this clear.
> Rollback version number to 0.5.0-dev

- src/client.d
- src/server.d
- Fixed: Impossible to login after changing password because plain-text was written to database
This is just a quick fix to get it working for now, a more robust method can be implemented in future.
> client.d: allow user to change password

- src/client.d
- src/db.d
- src/messages.d
- Fixed: Incorrect hash sent back to peer's client after successful Login was a hash of the hash instead of just hashing once
- Changed: Keep the hash instead of the plain `password` string in the User class of the client.d module
> Login encode_password hash in get_user

- src/client.d
- src/defines.d
- src/server.d
- Added: Show program name and version at startup with red-on-white unicode heart symbol `U+2665` as icon
- Added: Bright white background colour for block-highlighting text (black-on-white by default, or any foreground colour)
- Added: Bright `bold` text
- Renamed: Defined colour `black` to `norm` because it's just whatever normal is depending on the default terminal scheme
Can also specify a background colour and any foreground, for example `bg_w ~ blue` for blue on white. In this case, red-on-white is used on to represent the project's heart icon surrounded with left and right half blocks to make a white square `▌♥▐` ...
It is useful to verify at startup that the runtime terminal does support colour and unicode characters on the standard output.
> defines.d: bright white background and bold text ♥

- src/server.d
- Fixed: Segmentation fault when banning a user who is offline or doesn't exist (`ban` chat interface command)
> server.d: fix segmentation fault when banning offline user

- src/server.d
- Removed: `nbusers` command
- Added: Show count of the number of connected users in the response of the `users` command
- Changed: `users` command outputs one single user per line, showing only the username of each user
The verbosity of the full user info for each user would be excessive if there are a large number of users, whereas what is desired here is only the most pertinent information to be displayed in a plain list format.
> server.d: abbreviated users list response

- src/db.d
- src/server.d
- src/soulsetup.d
Instead of having to deal with adding new columns for new options in the future, use a single row per config option.
> db.d: simplify config storage

- src/client.d
- src/db.d
- src/server.d
- src/soulsetup.d
Some minor refactoring...
- Removed: Don't store a copy the MOTD template in the server.d module, because it is a trivial query so just get it directly from the database instead, in order to take immediate effect of a changed MOTD template instead of having to reload
- Changed: Renamed `%version%` replacer to `%sversion%` for server version, because it ought to be used less often
- Changed: Renamed `%userversion%` replacer to `%version%` for client version, because it avoids awkward concatenation
- Changed: Renamed `%nbusers%` replacer to `%users%` for number of connected users, because the "nb" term is uncommon
- Fixed: Use the replacer string in the default motd config setting, instead of hard-coding the server version into the stored text value at the point in time when the table is …
> Get MOTD template directly from config table during login

- src/client.d
- src/db.d
- src/server.d
- src/soulsetup.d
The ~previously~ unimplemented `level` field is required because otherwise the server owner cannot create other admins without fear of being deleted. This PR ~implements 3 admin levels~ _abolishes adding and removing admins from the admin chat interface_ in order to mitigate that issue and makes an improvement to setup...
- **Removed: `addadmin` and `deladmin` chat interface commands, only allow administration using soulsetup**
- Removed: `reload` command, since it's not required anymore, instead changes take effect immediately
- Removed: Don't maintain an `admins` list internally, instead refer directly to the `admins` table of the database
- Changed: Use newlines instead of spaces to separate names on the output of the `admins` command
- Changed: Use tabs instead of hyphens to indent …
> Simplify admins

- src/db.d
- src/soulsetup.d
In this PR, two existing functions are repurposed to get the number of users who are `privileged` or `banned` for informational display in soulsetup, but these functions could also be, for example, to count/list all users having at least a certain amount of `folders`, whose `speed` is between a given range, or any other kind of simple lookup query that is likely to be needed.
- Added: `count_users()` with filtering based on a range of minimum/maximum values of any given `filter_field`
- Added: `get_usernames()` with filtering based on a range of minimum/maximum values of any given `filter_field`
- Removed: `get_all_usernames()` unused function that was not referenced anywhere
- Fixed: A couple of minor typo's and layout tweaks in the soulsetup menus, for demonstrative purposes...
_Output …
> db.d: count_users() with filtering by any numeric field

- src/client.d
- src/db.d
- src/message_codes.d
- src/messages.d
- src/server.d
- src/soulsetup.d
- Removed: `writeln()`
- Added: `writefln()` because it does implicit format string conversions
- Added: Colourized usernames in some more cases
- Changed: "Sending ->" and "Receive <-" with arrows indicating direction in place of the word "message"
- Changed: Clarified the wording of some debug messages as to who is Telling who about UserStatus
- Fixed: Broken line continuations when debug logging is enabled
> writeln() -> writefln()

- src/client.d
- src/db.d
- src/server.d
Fixes two issues:
- Privileges don't decrement when a user is offline
- No way of knowing if user had privileges in the past (needed for the 'supporter' attribute in the login message)
The timestamp approach also reduces the number of writes to the database, since the timestamp is only updated when privileges are extended or reduced.
> Use expiration timestamps for user privileges

- src/room.d
- src/server.d
- src/soulsetup.d
Mostly reverts commit 2339eeab 
I don't need this workaround anymore, and there's no need for us to support anything other than current runtime environments (Bookworm, etc) for this project.
```
$ ldmd2 --version
LDC - the LLVM D compiler (1.30.0):
based on DMD v2.100.1 and LLVM 14.0.6
built with LDC - the LLVM D compiler (1.30.0)
Default target: x86_64-pc-linux-gnu
Host CPU: sandybridge
http://dlang.org - http://wiki.dlang.org/LDC
```
Thanks for doing this to help get me get up and running!
> Drop support for older versions of D and make safe

- src/client.d
- src/room.d
- src/server.d
- Changed: Avoid returning entire list of `users` objects just to do a `username` membership check
- Removed: Pointless iteration through `users` objects to check if iterating through `users` objects is going to happen
- Removed: `client.watched_by()` method, since it was only called (twice) by a single function
- Removed: `server.find_user()` method, since no function called it
- Added: `room.is_joined()` method for membership checking without exposing the entire `room.user_list`
Reduces unnecessary recursive iteration by several orders of magnitude.
> client.d: is_watching() membership check optimization

- src/db.d
- Removed: Two unreachable `return` statements, nothing is executed after `throw`ing an `Exception`.
> db.d: remove unreachable code

- .github/workflows/build.yml
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Related to https://github.com/soulfind-dev/soulfind/issues/31
> CI: add Linux arm64 build

- src/db.d
- src/setup/package.d
- Fixed: Display number of currently privileged users (excluding historic supporters) in Soulsetup Server Info
- Changed: num_users(, min, max) `uint` -> `ulong` to support timestamp values that are now used in the database
> soulsetup: fix num_users with active privileges in server info

- src/db.d
- Changed: Don't leave a reference to the most recently compiled SQL statement handing around for no reason.
> db.d: locally declare stmt variable

- src/server/messages.d
- src/server/user.d
- Fixed: A user could give way more privileges than he had, because the client provides the number of days to give, whereas the server calculates the remaining privileges in seconds, so this `>` comparison was off by a factor of 86400.
- Renamed `msg.time` -> `msg.days` to clarify that this integer value is [specified in days](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md#server-code-123) and not seconds.
This bug was found while working on https://github.com/slook/soulfind/commit/20522ac247cef79e25e0ec24636df1aa14c4834f that parses time values using the `Duration` data type to add or remove privileges, with the intent of reducing the risk of this type of confusion.
> GivePrivileges: fix time comparison between days and seconds

- src/db.d
It seems like a good idea to run some non-destructive query at startup so an error might be thrown if something serious is wrong with the database before attempting any writes. These commands are usually a no-op and so are very fast...
- Added: Run [integrity_check](https://www.sqlite.org/pragma.html#pragma_integrity_check) on all tables at startup to validate schema and output any warnings to debug(db)
- Added: Run [optimize](https://www.sqlite.org/pragma.html#pragma_optimize) on all tables at startup to analyze and build or update the autoindexes 
- Added: Run [optimize periodically](https://www.sqlite.org/lang_analyze.html#periodically_run_pragma_optimize_), i.e. when adding users. SQLite usually skips this unless the number of records have increased by 10-fold since last optimized. …
> db.d: run integrity check and optimize all tables at startup

- src/db.d
- Fixed: Throw an actual error code instead of the final result code (which is usually `0`)
- Removed: Hide the query string in debug(db) builds unless throwing an error, because it's not often helpful and is too noisy
- Changed: Always show complete text of error messages in all builds including release builds, rather than only codes.
Since the faulty implementation in #11, any thrown error was always [code 21 (SQLITE_MISUSE)](https://www.sqlite.org/rescode.html#misuse) "bad parameter or other API misuse" because the argument to `sqlite_errstr()` has to be an [error code rather than a result code](https://www.sqlite.org/rescode.html#result_codes_versus_error_codes). 
This PR corrects that mistake and produces a more helpful [extended error …
> db.d: implement extended error codes and throw relevant messages

- src/server/server.d
+ Fixed: Use correct output for `users banned` command without leading newline typo, the same as used for other outputs.
+ Added: Validate choice if the optional argument is specified for the `users` command, because its too easy to make a spelling mistake which leads to getting the wrong information.
> server.d: correct output for users banned command syntax

- README.md
- src/db.d
- src/server/server.d
- src/server/user.d
- src/setup/setup.d
Removes the admin table, and adds an expiration date for the admin status to the users table. This effectively ties the admin status to registered users only.
> Add expiration date for admin statuses

- src/db.d
- src/defines.d
- src/pwhash.d
- src/server/server.d
- src/server/user.d
- src/setup/setup.d
- src/tests/pwhash.d
Implements PBKDF2 password hashing with the help of D's std.digest module. Salts are generated using std.random's unpredictableSeed() function, which is cryptographically secure on most operating systems in recent D versions.
Hashed passwords are stored in the PHC string format:
`$<id>$<iterations>=<value>$<salt>$<hash>`
Includes unit tests.
While the database schema stays unchanged, previously registered users will not be able to log in, unless the soulsetup tool is used to remove them or change their passwords.
> Implement PBKDF2 password hashing
